-- Drop existing table if it exists
DROP TABLE IF EXISTS [PRODUCT];

CREATE TABLE [PRODUCT] (
    PRODUCTID VARCHAR(50) PRIMARY KEY,
    PRODUCTNAME VARCHAR(255) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    PRODUCTCATEGORY VARCHAR(100) NOT NULL,
    BARCODE VARCHAR(13) NOT NULL UNIQUE,
    SKU VARCHAR(50) NOT NULL UNIQUE,
    UNIT VARCHAR(50) NOT NULL,
    WEIGHT DECIMAL(10, 2) NOT NULL,
    PHOTO VARBINARY(MAX),
    SUPPLIERID VARCHAR(50) NOT NULL,
    BUYINGPRICE DECIMAL(10, 2) NOT NULL,
    SELLINGPRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT DECIMAL(5, 2) NOT NULL DEFAULT 0,
    TAX DECIMAL(5, 2) NOT NULL DEFAULT 0,
    MRP DECIMAL(10, 2) NOT NULL,
    STOCKQUANTITY INT NOT NULL DEFAULT 0,
    REORDERLEVEL INT NOT NULL,
    MINSTOCKLEVEL INT NOT NULL,
    ISEXPIRABLE BIT NOT NULL DEFAULT 0,
    EXPIRYDATE DATETIME,
    ISACTIVE BIT NOT NULL DEFAULT 1,
    RETURNABLE BIT NOT NULL DEFAULT 0
);
