-- Drop existing table if it exists
DROP TABLE IF EXISTS [SALE];

CREATE TABLE [SALE] (
    SALEID VARCHAR(50) PRIMARY KEY,
    INVOICENUMBER VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMERID VARCHAR(50),
    CASHIERID VARCHAR(50) NOT NULL,
    SALEDATE DATETIME NOT NULL DEFAULT GETDATE(),
    TOTALAMOUNT DECIMAL(10, 2) NOT NULL,
    DISCOUNTPERCENTAGE DECIMAL(5, 2) NOT NULL DEFAULT 0,
    DISCOUNTAMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    TAXPERCENTAGE DECIMAL(5, 2) NOT NULL DEFAULT 0,
    TAXAMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    GRANDTOTAL DECIMAL(10, 2) NOT NULL,
    PAIDAMOUNT DECIMAL(10, 2) NOT NULL,
    CHANGEAMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PAYMENTMETHOD VARCHAR(50) NOT NULL,
    SALESTATUS VARCHAR(50) NOT NULL DEFAULT 'COMPLETED',
    NOTES VARCHAR(500),
    CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
    MODIFIEDDATE DATETIME
);
-- Drop existing table if it exists
DROP TABLE IF EXISTS [SALEITEM];

CREATE TABLE [SALEITEM] (
    SALEITEMID VARCHAR(50) PRIMARY KEY,
    SALEID VARCHAR(50) NOT NULL,
    PRODUCTID VARCHAR(50) NOT NULL,
    BARCODE VARCHAR(13) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT VARCHAR(50) NOT NULL,
    UNITPRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNTPERCENTAGE DECIMAL(5, 2) NOT NULL DEFAULT 0,
    DISCOUNTAMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    TAXPERCENTAGE DECIMAL(5, 2) NOT NULL DEFAULT 0,
    TAXAMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    LINETOTAL DECIMAL(10, 2) NOT NULL,
    BATCHNUMBER VARCHAR(50),
    EXPIRYDATE DATETIME,
    ISRETURNED BIT NOT NULL DEFAULT 0,
    RETURNDATE DATETIME,
    RETURNQUANTITY INT DEFAULT 0,
    CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE()
);
