CREATE TABLE [SUPPLIER] (
    SUPPLIERID VARCHAR(50) PRIMARY KEY,
    SUPPLIERNAME VARCHAR(100) NOT NULL,
    PHONENUMBER VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    COMPANYNAME VARCHAR(100) NOT NULL,
    TAXID VARCHAR(50),
    PAYMENTTERMS VARCHAR(100),
    ISACTIVE BIT DEFAULT 1
);
